// One-time script: converts Census TopoJSON → SVG path strings for Ohio counties.
// Run: npm run generate-svg
// Requires devDependencies: us-atlas, d3-geo, topojson-client

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";
import { geoPath, geoAlbers } from "d3-geo";
import type { Topology } from "topojson-specification";
import type { FeatureCollection, Geometry } from "geojson";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OHIO_FIPS = "39";
const VIEW_WIDTH = 800;
const VIEW_HEIGHT = 700;

// Load Census county boundaries
const topoPath = resolve(__dirname, "../node_modules/us-atlas/counties-10m.json");
const topology = JSON.parse(readFileSync(topoPath, "utf-8")) as Topology;

// Convert to GeoJSON and filter to Ohio
const allCounties = feature(topology, topology.objects.counties) as FeatureCollection<Geometry>;
const ohioCounties = allCounties.features.filter((f) => String(f.id).startsWith(OHIO_FIPS));

console.log(`Found ${ohioCounties.length} Ohio counties`);

if (ohioCounties.length !== 88) {
  console.error(`Expected 88 counties, got ${ohioCounties.length}`);
  process.exit(1);
}

// Project with Albers centered on Ohio
const projection = geoAlbers()
  .center([0, 40.4])
  .rotate([82.7, 0])
  .parallels([39, 42])
  .fitSize([VIEW_WIDTH, VIEW_HEIGHT], { type: "FeatureCollection", features: ohioCounties });

const pathGenerator = geoPath(projection);

// Generate path strings, rounding coordinates to 1 decimal
const entries: Array<{ name: string; path: string }> = [];

for (const county of ohioCounties) {
  const name = county.properties?.name as string;
  if (!name) {
    console.error(`County ${county.id} has no name property`);
    process.exit(1);
  }

  const rawPath = pathGenerator(county);
  if (!rawPath) {
    console.error(`Failed to generate path for ${name}`);
    process.exit(1);
  }

  // Round numeric values to 1 decimal place
  const roundedPath = rawPath.replace(/(\d+\.\d+)/g, (match) => {
    return parseFloat(match).toFixed(1);
  });

  entries.push({ name, path: roundedPath });
}

// Sort alphabetically for stable output
entries.sort((a, b) => a.name.localeCompare(b.name));

// Write TypeScript file
const lines = entries.map(({ name, path }) => `  "${name}": "${path}",`);
const output = `// Generated by scripts/generate-ohio-svg.ts — do not edit manually.
// Source: us-atlas counties-10m.json (Census TIGER boundaries)
// Projection: Albers centered on Ohio, ${VIEW_WIDTH}x${VIEW_HEIGHT} viewBox
// Coordinates rounded to 1 decimal place

export const OHIO_COUNTIES: Record<string, string> = {
${lines.join("\n")}
};
`;

const outPath = resolve(__dirname, "../src/data/ohio-counties.ts");
writeFileSync(outPath, output, "utf-8");
console.log(`Wrote ${entries.length} counties to ${outPath}`);
