// Generated by scripts/generate-ohio-svg.ts — do not edit manually.
// Each entry maps a county name to its SVG path `d` attribute.
export const OHIO_COUNTIES: Record<string, string> = {
  // Will be populated by the generate script
};
